### ISSUE TITLE
Menu Scene

### ISSUE THREAD

**Issue by local-minimum** [local-minimum/ldjam43#10]
A train that runs in a short loop and passes a station.
Some buttons and text.

**Comment by lostminds** [comment]
Quick intro text to game mechanic. "Running a train line costs money, stay in business and keep your support up by getting the train to pass stations. And try not to run over too many people getting there, or their patience with you will run out."

**Comment by local-minimum** [comment]
Reasons might have to be put in text below the game to save time.
